# Site settings
title:               MhdAli
permalink:           pretty
markdown:            kramdown

# Setup
tagline:             'Personal Blog'
description:         'My personal blog and notes, reach me out on Twitter <a href="https://twitter.com/mhdali_" target="_blank">@mhdali_</a>'
url:                 https://mhdali.github.io/
baseurl:             ''
paginate:            5
excerpt_separator:   <!--more-->
github:
  repo:         https://github.com/mhdali

# About/contact
author:
  name:              MhdAli
  url:               https://twitter.com/mhdali_
  email:             ma.alfarra@gmail.com
